apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 6
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx
        type: nginx
    spec:
     containers:
     - name: nginx
       image: nginx:latest
