apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: redis
        type: redis
    spec:
     containers:
     - name: redis
       image: redis:latest
